services:
    update_project_info_service: '@Librecores\ProjectRepoBundle\Consumer\UpdateProjectInformation'
    librecores.util.githubapiservice: '@Librecores\ProjectRepoBundle\Service\GitHub\GitHubApiService'
    librecores.util.queuedispatcherservice: '@Librecores\ProjectRepoBundle\Service\QueueDispatcherService'
    librecores.util.markuptohtmlconverter:  '@App\Util\MarkupToHtmlConverter'
    app.form.type.project: '@Librecores\ProjectRepoBundle\Form\Type\ProjectType'
    app.form.type.organization: '@Librecores\ProjectRepoBundle\Form\Type\OrganizationType'
    librecores.form_extention.icon: '@Librecores\ProjectRepoBundle\Form\Extension\ButtonTypeIconExtension'
    librecores.form.type.purified_textarea: '@Librecores\ProjectRepoBundle\Form\Type\PurifiedTextareaType'
    librecores.form.transformer.html_purifier: '@Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer'
    validator.user_org_name: '@Librecores\ProjectRepoBundle\Validator\Constraints\UserOrgNameValidator'
    librecores_user_manager: '@Librecores\ProjectRepoBundle\Doctrine\UserManager'
    librecores_user_provider: '@Librecores\ProjectRepoBundle\Security\Core\User\LibreCoresUserProvider'
    librecores.user.registration_event_listener: '@Librecores\ProjectRepoBundle\EventListener\OAuthRegistrationListener'
    librecores_project_voter: '@Librecores\ProjectRepoBundle\Security\ProjectVoter'
    librecores.process_creator: '@App\Util\ProcessCreator'
    librecores.repocrawlerfactory: '@Librecores\ProjectRepoBundle\RepoCrawler\RepoCrawlerFactory'
