imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: packages/webpack_encore.yml }
    - { resource: packages/algolia_search.yml }
    - { resource: packages/doctrine_migrations.yml }
    - { resource: packages/doctrine.yml }
    - { resource: packages/fos_user.yml }
    - { resource: packages/framework.yml }
    - { resource: packages/hwi_oauth.yml }
    - { resource: packages/old_sound_rabbit_mq.yml }
    - { resource: packages/swiftmailer.yml }
    - { resource: packages/twig.yml }
