# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Twig date extension - http://twig-extensions.readthedocs.io/en/latest/date.html
    Twig\Extensions\DateExtension:
        autowire: false
        # Autowire inject a TranslatorInterface into the constructor of the extension. If that happens, the extension
        # thinks it can be translated -- but we don't have any translations available, therefore the autowire is set to
        # false

    FOS\UserBundle\Mailer\MailerInterface: '@fos_user.mailer'

    Librecores\ProjectRepoBundle\Command\UpdateReposCommand:
        arguments:
            $producer: '@old_sound_rabbit_mq.update_project_info_producer'

    App\Util\MarkupToHtmlConverter:
        arguments:
            - '@logger'
            - '@exercise_html_purifier.default'

    App\Util\GithubApiService:
        arguments:
            - '@security.token_storage'
            - '@app.cache.githubapi'
            - '@router'

    App\Util\QueueDispatcherService:
        calls:
            - [setContainer, ['@service_container']]

    App\Util\ProcessCreator: ~

