# config/packages/webpack_encore.yml
webpack_encore:
  # The path where Encore is building the assets - i.e. Encore.setOutputPath()
  output_path: '%kernel.project_dir%/web/build'
    # If multiple builds are defined (as shown below), you can disable the default build:
    # output_path: false

    # if using Encore.enableIntegrityHashes() and need the crossorigin attribute (default: false, or use 'anonymous' or 'use-credentials')
    # crossorigin: 'anonymous'

    # if you have multiple builds:
    # builds:
    # pass "frontend" as the 3rg arg to the Twig functions
    # {{ encore_entry_script_tags('entry1', null, 'frontend') }}

  # frontend: '%kernel.project_dir%/public/frontend/build'

  # Cache the entrypoints.json (rebuild Symfony's cache when entrypoints.json changes)
  # Available in version 1.2
  #cache: '%kernel.debug%'
