# All settings in this configuration can be overwritten in dev-vagrant.user.yml
---
librecores_domain: "librecores.devel"
mysql_host: "localhost"
web_user: "{{ ansible_ssh_user }}"
use_https: false

symfony_config:
  SYMFONY_ENV: dev
  SYMFONY_DEBUG: 1

# all secrets have dummy values for the local development setup
rabbitmq_admin_password: "password"
site_mysql_password: "password"
site_symfony_secret_token: "ThisTokenIsNotSoSecretChangeIt"
site_rabbitmq_password: "password"
blog_mysql_password: "password"
mysql_root_password: "password"

# sentry configuration
# sentry is disabled in development setups
site_sentry_dsn: ""
site_sentry_env: dev

# Require confirmation of the email address of newly registered users.
# Requires a working mailer setup. Add SMTP credentials in
# secrets/dev-vagrant.secrets.yml before enabling this setting.
site_user_email_confirmation_enabled: false

# Algolia
site_algolia_search_prefix: 'dev_'
