---
# get current AMI ID from http://cloud-images.ubuntu.com/locator/ec2/
# search for xenial amd64 hvm:ebs eu-west-1
ami_id: "ami-844e0bf7"
aws_region: "eu-west-1"

# Public IPs (EC2 Elastic IPs)
# Make sure to update the DNS entries with those IPs as well!
# stage.librecores.org
ip_public: "52.209.114.159"

librecores_domain: "stage.librecores.org"
web_user: "www-data"
mysql_host: "localhost"
use_https: true

env:
  SYMFONY_ENV: prod
  SYMFONY_DEBUG: 0
  NODE_ENV: production

# sentry configuration
site_sentry_env: staging

site_user_email_confirmation_enabled: true

# Algolia
site_algolia_search_prefix: 'staging_'
