- name: Install cloc
  get_url:
    url: https://github.com/AlDanial/cloc/releases/download/v1.72/cloc-1.72.pl
    dest: /usr/local/bin/cloc
    mode: 0755
    checksum: sha256:6ac5fbfed3d3c1f18688bf60079506ef0bfae212fd26e5e2f9baad2fd2b6e815    