---
- name: restart nginx
  service: name=nginx enabled=yes state=restarted

- name:    restart php7.0-fpm
  service: name=php7.0-fpm enabled=yes state=restarted

- name: restart rabbitmq
  service: name=rabbitmq-server enabled=yes state=restarted
